puts "The students of VIllains Academy"
puts "------------"
puts "Dr. Hanibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "Alex DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffery Baratheon"
puts "Norman Bates"
